version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weather-checker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lu1x99x8q4q4"
s3_prefix = "weather-checker"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

